---

          - name: install mysql-server8.0
            yum: name=mysql-server

          - name: service start
            service: 
                name: mysqld
                state: started
                enabled: yes
            tags: service_start

          - name: set password for root@localhost
            command: "mysqladmin -uroot password 123456"
            ignore_errors: yes
      
          - name: copy cnf
            template: 
                src: my.cnf.j2
                dest: /etc/my.cnf
            notify: restart mysqld


